### ISSUE TITLE
Error when an implementation of a java interface is used as parameter to a Java Object's Method

### ISSUE THREAD

**Issue by gcoleman72** [beeware/rubicon-java#61] opened 2021-07-23 05:54 UTC
**Describe the bug**
It seems to want to call the hashCode() method but the Python Object doesn't know about hashCode

**To Reproduce**
This guy is having the same problem doing the same thing as me.
   https://gist.github.com/telent/6409c94ff9a4f448ecbd6b5859718669
My Code:

        ILocationListener = JavaInterface('android/location/LocationListener')
        class location_helper(ILocationListener):

........

        _location_helper = location_helper()
        LocationManager = JavaClass('android/location/LocationManager')
        location_manager_object = self.activity.getSystemService('location')
        print(str(location_manager_object))
        location_manager = LocationManager(__jni__=java.NewGlobalRef(location_manager_object))
        print(str(location_manager))
        location_manager.requestLocationUpdates("gps", 0, 0.0, self._location_helper)
        
I uncommented line 32 of rubicon/java/api.py and added this at line 34
        print(str(pyinstance._methods))

Results:
07-23 15:35:03.969 15631 15631 I Python  : android.location.LocationManager@f81e026
07-23 15:35:03.972 15631 15631 I Python  : android.location.LocationManager@f81e026
07-23 15:35:03.983 15631 15631 D Python  : Native invocation 514799255360 :: hashCode
07-23 15:35:03.983 15631 15631 I Python  : PYTHON SIDE DISPATCH 514799255360 hashCode ()
07-23 15:35:03.984 15631 15631 I Python  : {'onLocationChanged': {(b'Landroid/location/Location;',)}, 'onProviderDisabled': {(b'Ljava/lang/String;',)}, 'onProviderEnabled': {(b'Ljava/lang/String;',)}, 'onStatusChanged': {(b'Ljava/lang/String;', b'I', b'Landroid/os/Bun
dle;')}}
07-23 15:35:03.984 15631 15631 E Python  : Error invoking callback
07-23 15:35:03.984 15631 15631 E Python  : Traceback (most recent call last):
07-23 15:35:03.984 15631 15631 E Python  :   File "/data/user/0/au.gov.aims.gregbee/files/python/user_code/app_packages/rubicon/java/api.py", line 37, in dispatch
07-23 15:35:03.985 15631 15631 E Python  :     if len(signatures) == 1:
07-23 15:35:03.985 15631 15631 E Python  : TypeError: object of type 'NoneType' has no len()

**Expected behavior**
I am pretty sure the error is coming from this line
      location_manager.requestLocationUpdates("gps", 0, 0.0, self._location_helper)
I want that line to run without an error

**Screenshots**

**Environment:**
 - Operating System: Developing on windows 10 for deployment to Android
 - Python version: 3.8
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.3.0
   - ...

**Additional context**

**Comment by freakboy3742** [comment] 2021-07-25 07:14
Thanks for the report. 

My experience has been that references to `hashCode()` are often a red herring; the underlying problem is usually a couple of levels higher up, but the problem manifests as an error evaluating `hashCode()`. The actual problem is usually an object that hasn't been instantiated correctly, or hasn't been stored correctly etc.

Two things to look into by way of debugging:
1. It's a little difficult to tell from the debug log you've provided - can you confirm that the error is actually coming from the `requestLocationUpdates` call, and not from the debug output lines a couple of lines earlier? 

2. Can you confirm that `self._location_listener` is set? From the code sample you've provided, a location listener has been instantiated, but it's not being assigned to self; so it's possible that the error is correct (of a fashion) - you may be passing in a null object (which, as the error says, doesn't have a hashCode... because it's a null). Adding debug output for `self._location_listener` would be especially helpful, as it will establish if the problem is with the creation of the location listener, or the invocation of the function that is using the listener.

**Comment by gcoleman72** [comment] 2021-07-25 23:26
My apologies. My code was a bit confusing. The class that I should have called location_listener was actually called location_helper but it certainly was set. I have renamed it to location_listener. Now I have two classes location_worker and location_listener. Source for the two classes and the output is below.

```
from rubicon.java import JavaClass, JavaInterface, java
from locations.location_listener import location_listener

LocationManager = JavaClass('android/location/LocationManager')

class location_worker():

    _location_listener = location_listener()
    activity = "activity not set"
    app = "not set"

    def set_app(self, app):
        print("I will set the app")
        self.app = app
        self.activity=app.native
        location_manager_object = self.activity.getSystemService('location')
        print(str(location_manager_object))
        location_manager = LocationManager(__jni__=java.NewGlobalRef(location_manager_object))
        print(str(location_manager))
        print(str(self._location_listener))
        self._location_listener.onLocationChange(None)
        self._location_listener.onStatusChanged(None, None, None)
        self._location_listener.onProviderEnabled(None)
        self._location_listener.onProviderDisabled(None)
        location_manager.requestLocationUpdates("gps", 0, 0.0, self._location_listener)
        print("I have set the app")
```

```
from rubicon.java import JavaInterface

ILocationListener = JavaInterface('android/location/LocationListener')

class location_listener(ILocationListener):
    latitude = -1
    longitude = -1
    status = "Not set"

    def onLocationChange(self, location):
        print ("location change")
        # latitude = location.getLatiude()
        # longitude = location.getLongitude()

    def onProviderDisabled(self, provider):
        print("GPS disabled")

    def onProviderEnabled(self, provider):
        print("GPS enabled")

    def onStatusChanged(self, provider, status, extras):
        print("Status change")
        # self.status = status

```

```
07-26 09:18:58.733  6784  6784 I Python  : I will set the app
07-26 09:18:58.743  6784  6784 I Python  : android.location.LocationManager@e9f587d
07-26 09:18:58.747  6784  6784 I Python  : android.location.LocationManager@e9f587d
07-26 09:18:58.747  6784  6784 I Python  : <location_listener: 10262>
07-26 09:18:58.747  6784  6784 I Python  : location change
07-26 09:18:58.747  6784  6784 I Python  : Status change
07-26 09:18:58.747  6784  6784 I Python  : GPS enabled
07-26 09:18:58.748  6784  6784 I Python  : GPS disabled
07-26 09:18:58.760  6784  6784 D Python  : Native invocation 522875625280 :: hashCode
07-26 09:18:58.761  6784  6784 I Python  : PYTHON SIDE DISPATCH 522875625280 hashCode ()
07-26 09:18:58.761  6784  6784 I Python  : {'onLocationChanged': {(b'Landroid/location/Location;',)}, 'onProviderDisabled': {(b'Ljava/lang/String;',)}, 'onProviderEnabled': {(b'Ljava/lang/String;',)}, 'onStatusChanged': {(b'Ljava/lang/String;', b'I', b'Landroid/os/Bun
dle;')}}
07-26 09:18:58.761  6784  6784 E Python  : Error invoking callback
07-26 09:18:58.761  6784  6784 E Python  : Traceback (most recent call last):
07-26 09:18:58.761  6784  6784 E Python  :   File "/data/user/0/au.gov.aims.gregbee/files/python/user_code/app_packages/rubicon/java/api.py", line 37, in dispatch
07-26 09:18:58.763  6784  6784 E Python  :     if len(signatures) == 1:
07-26 09:18:58.763  6784  6784 E Python  : TypeError: object of type 'NoneType' has no len()
07-26 09:18:58.763  6784  6784 D Python  : Native invocation done.
07-26 09:18:58.763  6784  6784 I Python  : I have set the app

```

**Comment by gcoleman72** [comment] 2021-07-27 01:08
I fixed this issue by initialising my variable inside the __init__ method. But now I am seeing this error.
```
07-27 11:03:09.440 14908 14908 F ov.aims.gregbe: runtime.cc:650] JNI DETECTED ERROR IN APPLICATION: bad arguments passed to void android.location.LocationManager.requestLocationUpdates(java.lang.String, long, float, android.location.LocationListener) (see above for details)
```
I am pretty sure that I am passing the correct arguments.
If I change this line
`location_manager.requestLocationUpdates("gps", 0, 0.0, self._location_listener)`
to this
`location_manager.requestLocationUpdates("gps", 0, 0, self._location_listener)`
I get a different error
```
07-27 11:07:24.006 15667 15667 E Python  : ValueError: Can't find Java instance method 'b'android/location/LocationManager'.requestLocationUpdates' matching argument signature 'b'Ljava/lang/String;IILandroid/location/LocationListener;''. Options are: dict_keys([b'Land
roid/location/LocationRequest;Landroid/app/PendingIntent;', b'Landroid/location/LocationRequest;Landroid/location/LocationListener;Landroid/os/Looper;', b'JFLandroid/location/Criteria;Landroid/app/PendingIntent;', b'Ljava/lang/String;JFLandroid/app/PendingIntent;', b'
Ljava/lang/String;JFLandroid/location/LocationListener;', b'JFLandroid/location/Criteria;Landroid/location/LocationListener;Landroid/os/Looper;', b'Ljava/lang/String;JFLandroid/location/LocationListener;Landroid/os/Looper;'])
```

**Comment by freakboy3742** [comment] 2021-08-07 05:16
At this point, my suspicion is that the call to `requestLocationUpdates` is actually succeeding; but that call is causing a call back on the location listener, and there's something going wrong with *that* invocation.

Changing the input arguments to 2 integers causes a type lookup failure, and the error is exactly what I'd expect - telling you that there's no version of `requestLocationUpdates` that matches `II` (two integers) as inputs.

Looking at [the docs for LocationListener](https://developer.android.com/reference/android/location/LocationListener), I'm seeing 2 discrepancies:

 * There's no `onFlushComplete` method, which is required by the interface
 * The `onLocationChange` method should be named `onLocationChanged`
 
If you make those two changes, does the error resolve itself?

**Comment by freakboy3742** [comment] 2022-03-29 01:26
Closing due to lack of activity. If you believe this issue is still present, please let us know and we can reopen.

**Closed by freakboy3742** 2022-03-29 01:26 UTC
Labels: bug
